apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vaz8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vaz8
    app.kubernetes.io/part-of: tkrw-pr712-0075-0022-app
  name: devfile-sample-vaz8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vaz8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vaz8
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0022-tenant/tkrw-pr712-0075-0022-app/devfile-sample-vaz8@sha256:1f4f52467a78f861e7947574941a89c3a727b6149b9a003c1e7ba41d85ec4e3a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
